### ISSUE TITLE
validation error

### ISSUE THREAD

**Issue by SaibotMagd** [nfdi4plants/arc-validate#36]
the command:
`bash arc-validate.sh -p /arc/cmqtl_val1_arc -v` inside the docker container gives me this error message

```
+ arc-validate -p /arc/cmqtl_val1_arc -v
Internal Error:                         
The option value was None (Parameter 'option')
"   at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option) in D:\a\_work\1\s\src\FSharp.Core\option.fs:line 13
   at ArcValidation.CvTokenHelperFunctions.CvContainer.isPartOfInvestigation@79-2.Invoke(ICvBase x)
   at Microsoft.FSharp.Collections.SeqModule.Exists[T](FSharpFunc`2 predicate, IEnumerable`1 source) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 641
   at Microsoft.FSharp.Collections.SeqModule.Exists[T](FSharpFunc`2 predicate, IEnumerable`1 source) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 641
   at ArcValidation.InformationExtraction.Investigation.getContactsContainer@60.Invoke(CvContainer cv) in /opt/arc-validate/src/ArcValidation/InformationExtraction.fs:line 60
   at Microsoft.FSharp.Collections.Internal.IEnumerator.next@246[T](FSharpFunc`2 f, IEnumerator`1 e, FSharpRef`1 started, Unit unitVar0) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 248
   at Microsoft.FSharp.Collections.Internal.IEnumerator.filter@236.System.Collections.IEnumerator.MoveNext() in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 250
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 966
   at ArcValidation.TestGeneration.Critical.Arc.ISA.generateISATests(ArcConfig arcConfig) in /opt/arc-validate/src/ArcValidation/TestGeneration/Critical/ArcISA.fs:line 22
   at ARCValidate.main(String[] argv) in /opt/arc-validate/src/arc-validate/Program.fs:line 29"
root@7d1289fefede:/opt/arc-validate# 

```

**Comment by omaus** [comment]
Could you provide the Investigation file ("isa.investigation.xlsx") of this ARC here? If it contains sensible data which is not suited for publicity, you can also email me (maus@nfdi4plants.org).

**Comment by SaibotMagd** [comment]
That's no problem since I used the openly published dataset from Micha Wijesingha Ahchige published @  https://git.nfdi4plants.org/micwij/cmqtl_val1_arc

**Comment by SaibotMagd** [comment]
I also tried: https://git.nfdi4plants.org/x.zhou/sample_arc_model from Xiaoran Zhou (same error message).
and: https://gitlab.nfdi4plants.de/martinkuhl/samplearc_proteomics  which leads to this error message:

```
+ arc-validate -p /arc/SampleARC_Proteomics -v
[14:53:26 ERR] Critical.Filesystem.DataPathNames.minimal1.mzLite failed in 00:00:00.0130000. 
Actual entity is not present: /arc/SampleARC_Proteomics/assays/assay1/isa.assay.xlsx in Worksheet Some(MS) at Cell: W2
   at ArcValidation.OntologyHelperFunctions.throwError@36.Invoke(String msg)
   at ArcValidation.OntologyHelperFunctions.throwError(FSharpFunc`2 failStringFunction, ValidationResult result) in /opt/arc-validate/src/ArcValidation/OntologyHelperFunctions.fs:line 36
   at ArcValidation.TestGeneration.Critical.Arc.FileSystem.generateArcFileSystemTests@73-16.Invoke(Unit unitVar0) in /opt/arc-validate/src/ArcValidation/TestGeneration/Critical/ArcFileSystem.fs:line 73
   at Expecto.Impl.execTestAsync@569-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 508 <Expecto>
[14:53:26 ERR] Critical.Filesystem.DataPathNames.minimal2.mzLite failed in 00:00:00.0130000. 
Actual entity is not present: /arc/SampleARC_Proteomics/assays/assay1/isa.assay.xlsx in Worksheet Some(MS) at Cell: W3
   at ArcValidation.OntologyHelperFunctions.throwError@36.Invoke(String msg)
   at ArcValidation.OntologyHelperFunctions.throwError(FSharpFunc`2 failStringFunction, ValidationResult result) in /opt/arc-validate/src/ArcValidation/OntologyHelperFunctions.fs:line 36
   at ArcValidation.TestGeneration.Critical.Arc.FileSystem.generateArcFileSystemTests@73-16.Invoke(Unit unitVar0) in /opt/arc-validate/src/ArcValidation/TestGeneration/Critical/ArcFileSystem.fs:line 73
   at Expecto.Impl.execTestAsync@569-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 508 <Expecto>
[14:53:26 ERR] Critical.Filesystem.DataPathNames.minimal3.mzLite failed in 00:00:00.0130000. 
Actual entity is not present: /arc/SampleARC_Proteomics/assays/assay1/isa.assay.xlsx in Worksheet Some(MS) at Cell: W4
   at ArcValidation.OntologyHelperFunctions.throwError@36.Invoke(String msg)
   at ArcValidation.OntologyHelperFunctions.throwError(FSharpFunc`2 failStringFunction, ValidationResult result) in /opt/arc-validate/src/ArcValidation/OntologyHelperFunctions.fs:line 36
   at ArcValidation.TestGeneration.Critical.Arc.FileSystem.generateArcFileSystemTests@73-16.Invoke(Unit unitVar0) in /opt/arc-validate/src/ArcValidation/TestGeneration/Critical/ArcFileSystem.fs:line 73
   at Expecto.Impl.execTestAsync@569-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 508 <Expecto>
[14:53:26 ERR] Critical.Filesystem.DataPathNames.minimal4.mzLite failed in 00:00:00.0130000. 
Actual entity is not present: /arc/SampleARC_Proteomics/assays/assay1/isa.assay.xlsx in Worksheet Some(MS) at Cell: W5
   at ArcValidation.OntologyHelperFunctions.throwError@36.Invoke(String msg)
   at ArcValidation.OntologyHelperFunctions.throwError(FSharpFunc`2 failStringFunction, ValidationResult result) in /opt/arc-validate/src/ArcValidation/OntologyHelperFunctions.fs:line 36
   at ArcValidation.TestGeneration.Critical.Arc.FileSystem.generateArcFileSystemTests@73-16.Invoke(Unit unitVar0) in /opt/arc-validate/src/ArcValidation/TestGeneration/Critical/ArcFileSystem.fs:line 73
   at Expecto.Impl.execTestAsync@569-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 508 <Expecto>
[14:53:26 ERR] Critical.Filesystem.DataPathNames.minimal1.prot failed in 00:00:00. 
Actual entity is not present: /arc/SampleARC_Proteomics/assays/assay1/isa.assay.xlsx in Worksheet Some(Computation analysis) at Cell: K2
   at ArcValidation.OntologyHelperFunctions.throwError@36.Invoke(String msg)
   at ArcValidation.OntologyHelperFunctions.throwError(FSharpFunc`2 failStringFunction, ValidationResult result) in /opt/arc-validate/src/ArcValidation/OntologyHelperFunctions.fs:line 36
   at ArcValidation.TestGeneration.Critical.Arc.FileSystem.generateArcFileSystemTests@73-16.Invoke(Unit unitVar0) in /opt/arc-validate/src/ArcValidation/TestGeneration/Critical/ArcFileSystem.fs:line 73
   at Expecto.Impl.execTestAsync@569-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 508 <Expecto>
[14:53:26 ERR] Critical.Filesystem.DataPathNames.minimal2.prot failed in 00:00:00. 
Actual entity is not present: /arc/SampleARC_Proteomics/assays/assay1/isa.assay.xlsx in Worksheet Some(Computation analysis) at Cell: K3
   at ArcValidation.OntologyHelperFunctions.throwError@36.Invoke(String msg)
   at ArcValidation.OntologyHelperFunctions.throwError(FSharpFunc`2 failStringFunction, ValidationResult result) in /opt/arc-validate/src/ArcValidation/OntologyHelperFunctions.fs:line 36
   at ArcValidation.TestGeneration.Critical.Arc.FileSystem.generateArcFileSystemTests@73-16.Invoke(Unit unitVar0) in /opt/arc-validate/src/ArcValidation/TestGeneration/Critical/ArcFileSystem.fs:line 73
   at Expecto.Impl.execTestAsync@569-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 508 <Expecto>
[14:53:26 ERR] Critical.Filesystem.DataPathNames.minimal3.prot failed in 00:00:00. 
Actual entity is not present: /arc/SampleARC_Proteomics/assays/assay1/isa.assay.xlsx in Worksheet Some(Computation analysis) at Cell: K4
   at ArcValidation.OntologyHelperFunctions.throwError@36.Invoke(String msg)
   at ArcValidation.OntologyHelperFunctions.throwError(FSharpFunc`2 failStringFunction, ValidationResult result) in /opt/arc-validate/src/ArcValidation/OntologyHelperFunctions.fs:line 36
   at ArcValidation.TestGeneration.Critical.Arc.FileSystem.generateArcFileSystemTests@73-16.Invoke(Unit unitVar0) in /opt/arc-validate/src/ArcValidation/TestGeneration/Critical/ArcFileSystem.fs:line 73
   at Expecto.Impl.execTestAsync@569-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 508 <Expecto>
[14:53:26 ERR] Critical.Filesystem.DataPathNames.minimal4.prot failed in 00:00:00. 
Actual entity is not present: /arc/SampleARC_Proteomics/assays/assay1/isa.assay.xlsx in Worksheet Some(Computation analysis) at Cell: K5
   at ArcValidation.OntologyHelperFunctions.throwError@36.Invoke(String msg)
   at ArcValidation.OntologyHelperFunctions.throwError(FSharpFunc`2 failStringFunction, ValidationResult result) in /opt/arc-validate/src/ArcValidation/OntologyHelperFunctions.fs:line 36
   at ArcValidation.TestGeneration.Critical.Arc.FileSystem.generateArcFileSystemTests@73-16.Invoke(Unit unitVar0) in /opt/arc-validate/src/ArcValidation/TestGeneration/Critical/ArcFileSystem.fs:line 73
   at Expecto.Impl.execTestAsync@569-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 508 <Expecto>
[14:53:26 ERR] Critical.ISA.Semantic.Investigation.Person.Person1 [David Zimmer].Affiliation failed in 00:00:00. 
Actual entity is not present: /arc/SampleARC_Proteomics/isa.investigation.xlsx
   at ArcValidation.OntologyHelperFunctions.throwError@36.Invoke(String msg)
   at ArcValidation.OntologyHelperFunctions.throwError(FSharpFunc`2 failStringFunction, ValidationResult result) in /opt/arc-validate/src/ArcValidation/OntologyHelperFunctions.fs:line 36
   at ArcValidation.TestGeneration.Critical.Arc.ISA.generateISATests@45-16.Invoke(Unit unitVar0) in /opt/arc-validate/src/ArcValidation/TestGeneration/Critical/ArcISA.fs:line 45
   at Expecto.Impl.execTestAsync@569-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 508 <Expecto>
[14:53:26 ERR] Critical.ISA.Semantic.Investigation.Person.Person2 [Martin Kuhl].Affiliation failed in 00:00:00. 
Actual entity is not present: /arc/SampleARC_Proteomics/isa.investigation.xlsx
   at ArcValidation.OntologyHelperFunctions.throwError@36.Invoke(String msg)
   at ArcValidation.OntologyHelperFunctions.throwError(FSharpFunc`2 failStringFunction, ValidationResult result) in /opt/arc-validate/src/ArcValidation/OntologyHelperFunctions.fs:line 36
   at ArcValidation.TestGeneration.Critical.Arc.ISA.generateISATests@45-16.Invoke(Unit unitVar0) in /opt/arc-validate/src/ArcValidation/TestGeneration/Critical/ArcISA.fs:line 45
   at Expecto.Impl.execTestAsync@569-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 508 <Expecto>

```

**Comment by SaibotMagd** [comment]
And: https://git.nfdi4plants.org/brilator/samplearc_rnaseq

```
+ arc-validate -p /arc/samplearc_rnaseq -v
Internal Error:                         
Could not find a part of the path '/arc/samplearc_rnaseq/studies'.
"   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetDirectories(String path)
   at ArcValidation.TestGeneration.Critical.Arc.FileSystem.generateArcFileSystemTests(ArcConfig arcConfig) in /opt/arc-validate/src/ArcValidation/TestGeneration/Critical/ArcFileSystem.fs:line 51
   at ARCValidate.main(String[] argv) in /opt/arc-validate/src/arc-validate/Program.fs:line 29"
root@7d1289fefede:/opt/arc-validate# bash arc-validate.sh -p /arc/samplearc_rnaseq -v
+ arc-validate -p /arc/samplearc_rnaseq -v
Internal Error:                         
The option value was None (Parameter 'option')
"   at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option) in D:\a\_work\1\s\src\FSharp.Core\option.fs:line 13
   at ArcValidation.CvTokenHelperFunctions.CvContainer.isPartOfInvestigation@79-2.Invoke(ICvBase x)
   at Microsoft.FSharp.Collections.SeqModule.Exists[T](FSharpFunc`2 predicate, IEnumerable`1 source) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 641
   at Microsoft.FSharp.Collections.SeqModule.Exists[T](FSharpFunc`2 predicate, IEnumerable`1 source) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 641
   at ArcValidation.InformationExtraction.Investigation.getContactsContainer@60.Invoke(CvContainer cv) in /opt/arc-validate/src/ArcValidation/InformationExtraction.fs:line 60
   at Microsoft.FSharp.Collections.Internal.IEnumerator.next@246[T](FSharpFunc`2 f, IEnumerator`1 e, FSharpRef`1 started, Unit unitVar0) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 248
   at Microsoft.FSharp.Collections.Internal.IEnumerator.filter@236.System.Collections.IEnumerator.MoveNext() in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 250
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 966
   at ArcValidation.TestGeneration.Critical.Arc.ISA.generateISATests(ArcConfig arcConfig) in /opt/arc-validate/src/ArcValidation/TestGeneration/Critical/ArcISA.fs:line 22
   at ARCValidate.main(String[] argv) in /opt/arc-validate/src/arc-validate/Program.fs:line 29"

```

So I started to try every dataset I could find in the plants-datahub, but couldn't find one working.

**Comment by omaus** [comment]
There was an error in handling filepaths in the current ARC Validation version which I fixed yesterday. Maybe this also fixed this issue...

Otherwise, we will launch the new version of the Validation soon™ which will have this bug fixed.

**Comment by MicheleBortol** [comment]
Hi, I am reviving this issue because I have encountered the same error as @SaibotMagd I have this issue both with the docker container and with the CI/CD pipeline on datahub. You can find the pipeline error here:[https://git.nfdi4plants.org/michele.bortolomeazzi/mben_resolve/-/jobs/2532]( https://git.nfdi4plants.org/michele.bortolomeazzi/mben_resolve/-/jobs/2532)

This is the error I am getting from Docker:
```
root@d7ca40cef5e0:/arc# ls -alh
total 48K
drwxr-xr-x  8 root root 4.0K Nov 22 16:30 . 
drwxr-xr-x 22 root root 4.0K Nov 24 09:23 ..
drwxr-xr-x  2 root root 4.0K Nov 22 15:31 .arc
drwxr-xr-x  9 root root 4.0K Nov 22 16:30 .git
-rw-r-----  1 root root 1.8K Nov 22 15:31 .gitattributes
-rw-r--r--  1 root root  642 Nov 22 16:30 README.md
drwxr-xr-x  3 root root 4.0K Nov 22 15:31 assays
-rw-r--r--  1 root root 4.2K Nov 22 15:31 isa.investigation.xlsx
drwxr-xr-x  3 root root 4.0K Nov 22 15:31 runs
drwxr-xr-x  3 root root 4.0K Nov 22 15:32 studies
drwxr-xr-x  3 root root 4.0K Nov 22 15:32 workflows

root@d7ca40cef5e0:/arc# arc-validate -p .
Internal Error:
The option value was None (Parameter 'option')
"   at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option) in D:\a\_work\1\s\src\FSharp.Core\option.fs:line 13
at ArcValidation.CvTokenHelperFunctions.CvContainer.isPartOfInvestigation@79-2.Invoke(ICvBase x)
at Microsoft.FSharp.Collections.SeqModule.Exists[T](FSharpFunc`2 predicate, IEnumerable`1 source) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 641
at Microsoft.FSharp.Collections.SeqModule.Exists[T](FSharpFunc`2 predicate, IEnumerable`1 source) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 641
at ArcValidation.InformationExtraction.Investigation.getContactsContainer@60.Invoke(CvContainer cv) in /opt/arc-validate/src/ArcValidation/InformationExtraction.fs:line 60
at Microsoft.FSharp.Collections.Internal.IEnumerator.next@246[T](FSharpFunc`2 f, IEnumerator`1 e, FSharpRef`1 started, Unit unitVar0) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 248
at Microsoft.FSharp.Collections.Internal.IEnumerator.filter@236.System.Collections.IEnumerator.MoveNext() in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 250
at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 966
at ArcValidation.TestGeneration.Critical.Arc.ISA.generateISATests(ArcConfig arcConfig) in /opt/arc-validate/src/ArcValidation/TestGeneration/Critical/ArcISA.fs:line 22
at ARCValidate.main(String[] argv) in /opt/arc-validate/src/arc-validate/Program.fs:line 29"
```
